replicaCount: 3
image:
  repository: "274394226013.dkr.ecr.ap-south-1.amazonaws.com/auth-service"
  tag: 02a9bd21331d4ab10f92a54945a9505768f252a0
resources:
  requests: { cpu: "200m", memory: "256Mi" }
  limits: { cpu: "1000m", memory: "512Mi" }
autoscaling: { enabled: true, minReplicas: 3, maxReplicas: 10, targetCPUUtilizationPercentage: 60 }
deployment:
  enabled: false 
